# Generated by Django 5.1.15 on 2026-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0064_comment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="comment_task_id_75751a_idx",
            old_name="comment_task_id_8452af_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="comment_annotat_300401_idx",
            old_name="comment_annotat_250aaf_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="comment_draft_i_c4277d_idx",
            old_name="comment_draft_i_0d8a55_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="comment_project_87decd_idx",
            old_name="comment_project_b6d73a_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="comment_task_id_99bc43_idx",
            old_name="comment_task_is_5d9605_idx",
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
